#+TITLE: haskell 学习 - 1
#+DATE: 2026-08-26
#+KEYWORDS: haskell
#+SETUPFILE: ../../setupfiles/level-post.org

在学习 Rust
的过程中听说它受到了一些函数式语言的影响，同时也听说很多现代语言都在接受函数式语言的特性，
我对函数式语言有了很大的兴趣。之后了解了很多函数式语言，比如
Lisp，Racket，scheme，Ocaml，Haskell 等。
接触这些语言之后，打算深入学习一个。

Lisp 以及它的方言是动态类型，Ocaml
为了工程化有一些命令式语言的特性，允许非纯函数等，虽然它们都是历史
很深远的语言，但是我还是选择了学习
Haskell。一方面我不是为了实现一个非常高性能的程序，只是为了学习函数式
这种范式，我希望使用函数式的方式进行思考，使用递归和迭代的方式进行数据处理；另一方面，Haskell
的类型类
系统非常吸引我，能使用简单的函数和类型系统实现比较复杂或自定义的的数据处理方式。

* 函数式基础
纯函数是指函数内不管理内部状态，相同的输入必然得到相同的输出。

Haskell 的所有对象都是函数。这样讲是因为虽然 Haskell
有变量，但是都是不可变变量。因此可以看作不接受参数，
直接返回一个常量的纯函数。因此可以进一步认为 Haskell 内只有函数。

这样的推论并不严谨，但是 Haskell
内确实可以把直接返回常量的函数当作全局不可变变量使用。

* 第一个 Haskell 函数
Haskell 自带一个 REPL 执行环境 ghci，不必从 main 函数开始，自由且随意

让我们从第一个函数开始

#+begin_src haskell
ghci> add1 x = x + 1
ghci> add1 2
3
#+end_src

这是 Haskell 定义函数的语法，第一个部分为函数名，后续直到 '='
之前的每个部分代表参数，'=' 之后为函数体。 Haskell
的函数默认为纯函数，直接返回函数体的计算结果。

这个函数非常简单，接受一个参数，返回这个参数 +1 的值，'add1 2' 直接返回
3。

定义函数和其他语言没什么区别，只是不需要写很多命令式语言中的 =return=
，直接返回函数体的计算结果， Haskell 中的 =return= 有其他用途。

虽然像 Python 一样有 REPL 环境，但是实际上 Haskell 是一个强类型语言，在
ghci 中的函数定义可以 通过 =:t= 可以查看这个函数的类型标签。

#+begin_src haskell
ghci> :t add1
add1 :: Num a => a -> a
#+end_src

Num 是一个类型类，它包含了很多数字类型，例如 Int，Double 等，ghci
中可以通过 =:info= 查看

#+begin_src haskell
ghci> :info Num
type Num :: * -> Constraint
class Num a where
  (+) :: a -> a -> a
  (-) :: a -> a -> a
  (*) :: a -> a -> a
  negate :: a -> a
  abs :: a -> a
  signum :: a -> a
  fromInteger :: Integer -> a
  {-# MINIMAL (+), (*), abs, signum, fromInteger, (negate | (-)) #-}
    -- Defined in ‘GHC.Internal.Num’
instance Num Double -- Defined in ‘GHC.Internal.Float’
instance Num Float -- Defined in ‘GHC.Internal.Float’
instance Num Int -- Defined in ‘GHC.Internal.Num’
instance Num Integer -- Defined in ‘GHC.Internal.Num’
instance Num Word -- Defined in ‘GHC.Internal.Num’
#+end_src

类型类一个很强大的系统，且并不适合在这里详细说明，后面的部分再提。

最后几行 instance 表示 Double，Float，Int，Intger，Word 都是 Num
类型类的实例，都实现了 Num 类型类提供的几个函数， 都属于 Num 类型约束。

说回函数的类型标签，拆解一下：

- =Num a= 表示 a 是 Num 的一个实例，也就是上面提到的几个具体类型
- ==>= 表示前面的 a 的约束在后续的 a 上生效
- =a -> a= 表示接受一个 a 类型的参数，返回一个 a 类型的结果

运行 =add1 2= 时返回 3 ，运行 =add1 2.0= 时返回 3.0 ，这意味着 =add1=
这个函数会随着输入类型的改变，改变输出的类型，
这与我们拆解后看到的结论相符，它并不返回一个特定类型，而是 Num
约束中与输入类型 a 相同的类型，这就是 Haskell 的类型推导。

* 多个参数的函数
很多函数都不止一个参数，Haskell 中的大部分函数当然也是。

ghci 中默认没有 add 函数，我们放心大胆的定义一个

#+begin_src haskell
ghci> add x y = x + y
ghci> add 1 2
3
ghci> :t add
add :: Num a => a -> a -> a
#+end_src

可以看到 =a -> a -> a= 表示接受两个类型为 a 的参数，得到一个类型为 a
的结果

这并不像有的语言中用逗号分割参数列表，所以初次接触可能有点怪异，不过我们马上就来了解这个语法的深意

* 部分应用函数
大部分语言调用函数的方式是 =add(1, 2)= ，然后获得一个返回值，但是
Haskell 不一样，它可以部分应用函数

#+begin_src haskell
ghci> add2 = add 2
ghci> :t add2
add2 :: Num a => a -> a
ghci> add2 1
3
#+end_src

=add2 = add 2= 很明显只给 =add=
提供了一个参数，但是并不像其他语言一样报错，并且也成功给 =add2= 赋值了

=:t add2=
查看签名可以看到，这是一个接受一个参数的函数，为了验证这一点，使用
=add2 1= 运行这个函数，成功得到 3 ，这说明，=add2= 确实是一个函数

这就是部分应用函数，使用了 λ 演算中柯里化 (Currying) 的概念

柯里化是为了将 λ
演算中接受多个参数的函数简化为只接受一个参数并返回一个新函数的函数，这样只需要将每个函数都当作只有一个参数就行，
更便于对函数进行分析。JavaScript 中的闭包，也是使用了柯里化的概念

这样再来看 =add= 函数的签名 =add :: Num a => a -> a -> a= ，可以看作
=add :: Num a => a -> (a -> a)= ，表示接受一个 类型为 a 的参数，返回一个
*返回值类型为 a ，参数类型为 a 的函数* ，这就是柯里化

那么解释 =add 1 2= 也很简单，从左到右，=add 1= 返回一个将参数 +1
的函数，并应用到 2 上，最终返回 3

之前查看 Num 类型类的实例时，看到 Num 定义了几个接口，其中包括
=(+)=，=(*)=，=(-)=，这几个运算符，它们虽然不是用前缀方式调用的，
但是也确实是函数，用它们实现部分应用用函数更加简单

#+begin_src haskell
ghci> :t (+2)
(+2) :: Num a => a -> a
ghci> :t (*2)
(*2) :: Num a => a -> a
ghci> :t (2-)
(2-) :: Num a => a -> a
#+end_src

=-2= 会被识别为常量 -2 ，因此这里用 =(2-)= 做例子

部分应用，或者说柯里化，可以将一个比较复杂的多参数函数简化为一个只接受少量参数的函数，更重要的是在与高阶函数的配合上非常好用

* 高阶函数
高阶函数是接受函数作为参数的函数，例如一个非常常用的函数 map

#+begin_src haskell
ghci> :t map
map :: (a -> b) -> [a] -> [b]
#+end_src

它接受一个函数，然后接受一个数组，返回一个数组，接受的函数签名要为
=a -> b= 其中 a 和 b 可以相同， 并将这个函数应用到数组的每一个元素上

使用方式

#+begin_src haskell
ghci> map (+1) [1, 2, 3]
[2,3,4]
#+end_src

=(+1)= 签名为 =a -> a= ，匹配 =a -> b= 这个更大的要求，应用到数组
=[1, 2, 3]= 的每个元素上得到 =[2, 3, 4]=

还可以应用一个签名为 =a -> b= 的函数

例如 =show= ，它是一个处理输出的函数，负责将值转换为字符串

#+begin_src haskell
ghci> :t show
show :: Show a => a -> String
ghci> show 1
"1"
ghci> map show [1, 2, 3]
["1","2","3"]
#+end_src

show 的签名为 =a -> String= 符合 map 第一个参数的要求，应用到数组
=[1, 2, 3]= 上得到 =["1", "2", "3"]=

map 也可以作为参数的一部分，构成一个部分应用函数

#+begin_src haskell
ghci> map (map show) [[1,2,3], [2,3,4], [3,4,5]]
[["1","2","3"],["2","3","4"],["3","4","5"]]
#+end_src

外层的 map 将 map show
应用到外层数组的每个元素上，每个元素都是一个数组，然后对于每一个数组，map
show 将 show 应用到每个具体的值上

这里的 =(map show)= 就是一个部分应用函数

除此之外还有一些高阶函数，例如
fliter，foldl，foldr，都是接受函数作为其中一个参数的函数

#+begin_src haskell
ghci> :t filter
filter :: (a -> Bool) -> [a] -> [a]
ghci> :t foldl
foldl :: Foldable t => (b -> a -> b) -> b -> t a -> b
ghci> :t foldr
foldr :: Foldable t => (a -> b -> b) -> b -> t a -> b
#+end_src

* 惰性求值
** 无穷列表
Haskell 支持惰性求值，其中一个体现就是无穷列表

无穷列表没办法直接在 ghci 中打印出来，可以使用 =take= 取出前几个元素

#+begin_src haskell
ghci> take 10 [1..]
[1,2,3,4,5,6,7,8,9,10]
ghci> take 20 [1,3..]
[1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39]
ghci> take 5 [2,2..]
[2,2,2,2,2]
ghci> take 5 [3,2..]
[3,2,1,0,-1]
ghci> take 5 [2.0,2.1..]
[2.0,2.1,2.2,2.3000000000000003,2.4000000000000004]
#+end_src

无穷数字列表有几种形式，一种是 =[n..]= ，表示从 n 开始每项 +1
的数字列表，另一种是 =[n,m..]= ，表示从 n 开始， 每项 +(m-n)
的数字列表，这个值可以是任意数。

除了数字列表，还可以是 Char 列表

#+begin_src haskell
ghci> take 5 ['a'..]
"abcde"
#+end_src

这也是一个函数

#+begin_src haskell
ghci> :t ([2..])
([2..]) :: (Num a, Enum a) => [a]
#+end_src

这是一个已经应用了的函数，直接返回数组，但是可以看出数组中元素的类型需要满足
Enum 约束

除了这样的无穷列表外，还可以其他一些函数定义无穷列表，例如
=repeat= ， =cycle= 等

还可以用迭代或递归的方式定义，例如斐波那契数列，它是一个直接返回一个列表的函数

#+begin_src haskell
ghci> fibs = 0:1:zipWith (+) fibs (tail fibs)
ghci> take 10 fibs
[0,1,1,2,3,5,8,13,21,34]
#+end_src

tail 取列表除第一个元素外的后面所有元素

zipWith
是使用一个函数将两个列表合并为一个列表的函数，这里用加法将两个列表错位相加：

- fibs = 0:1:[...a]
- 计算 [...a] ，fibs + (tail fibs) 的第一项 => 取 fibs[0] + fibs[1] 得到
  fibs[2] = 1
- fibs = 0:1:1:[...b]
- 计算 [...b] ，fibs + (tail fibs) 的第二项 => 取 fibs[1] + fibs[2] 得到
  fibs[3] = 2
- fibs = 0:1:1:2:[...c]
- 计算 [...c] ...

就这样无限迭代下去

惰性求值的优势在于，使用这个值的时候才进行求值，因此如果按照常规命令式语言的规则对
fibs 函数进行分析， 它会不断调用自身而计算不出结果，但是在 Haskell
中这是可以实现的。

** 惰性求值函数
在前面提到 foldl 函数时，很多教程会指出，用 foldl
对无穷列表进行计算时要小心，因为可能陷入无限循环
导致卡死。虽然使用变量捕获 foldl
的调用过程时不会卡死，但是当真正使用这个变量时还是一定会卡死，这可能在
一些较为复杂的处理过程中不容易发现。

解决方法一般是使用 foldr ，接下来说明 foldl 和 foldr 不同的地方

foldl 和 foldr 的功能很强大，但是逻辑很简单

#+begin_src haskell
-- foldl
foldl f z [] = z
foldl f z (x:xs) = foldl f (f z x) xs

-- foldr
foldr f z [] = z
foldr f z (x:xs) = f x (foldr f z xs)
#+end_src

这里不同点在于，foldl 的递归中，foldl
自身在最外层，它自己决定是否停止递归，而 foldr 中，它先调用 f ， 可以由
f 的结果决定是否停止递归。例如 f 是一个在某个条件下忽略第二个参数的函数

#+begin_src haskell
foo x y
    | x > 10 = x
    | otherwise = x + y
#+end_src

使用 foldr 时，当 foo 的第一个参数的值大于 10
，忽略第二个参数，直接返回，避免了计算后续的 foldr

梳理一下

#+begin_quote
foldr foo 0 (1:[2..]) = foo 1 (foldr foo 0 [2..])\\
= 1 + (foldr foo 0 [2..])\\
= 1 + (foo 2 (foldr foo 0 [3..]))\\
= 1 + (2 + (foldr foo 0 [3..]))\\
= 1 + (2 + (3 + (foldr foo 0 [4..])))\\
= ...\\
= 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + foo 11 (foldr foo 0 [12..])\\
= 1 + ... + 11\\
= 66
#+end_quote

#+begin_src haskell
ghci> foldr foo 0 [1..]
66
#+end_src

但是使用 foldl 时，只能杀死进程，简单梳理一下 foldl 的流程

#+begin_quote
foldl foo 0 (1:[2..]) = foldl (foo 0 1) [2..]\\
= foldl foo 1 [2..]\\
= foldl (foo 1 2) [3..]\\
= foldl foo 3 [3..]\\
= foldl (foo 3 3) [4..]\\
= ...\\
= foldl foo 15 [6..]\\
= foldl (foo 15 6) [7..]\\
= foldl foo 15 [7..]\\
= foldl (foo 15 7) [8..]\\
= foldl foo 15 [8..]
#+end_quote

最外层始终是 foldl ，而 foldl
在列表处理完之前永远也不会返回，所以它永远不会停止

从这两个例子可以看到，Haskell 的惰性求值针对的是不需要立即使用的值，例如
foo 的第二个参数，或者 短路运算符 || 和 &&
的第二个参数。这几个函数都是在第一个参数满足某个条件时无须计算第二个参数的函数，
因此获得了惰性计算的能力。

除此之外，Haskell 对于数据构造器也是惰性求值的，例如 :
函数，它负责拼接数组

以 foldr 为例

#+begin_src haskell
ghci> take 10 $ foldr (\x y -> (show y):x) [] [1..]
["1","2","3","4","5","6","7","8","9","10"]
#+end_src

: 函数其实并不像 foo 函数那样有明确的判断语句，但是 Haskell
对数据构造器的规则是，在数据构造器被匹配之前，
它右边的内容绝对不会被计算

因此使用 : 函数，实际上返回的是
="1" : (foldr (\x y -> (show y):x) [] [2..]=
这个整体，右边是一个待计算的 块。在 ghci
中，因为数值默认打印，因此对整个数组会进行求值。如果使用 =take=
取出前几个元素，在实际取值时
才真正计算右边的部分，取值数量足够了就自动抛弃剩余还未计算的部分，这部分应该是
=flodr (\x y -> (show y):x) [] [11..]= ，
但是它还是在数据构造器的右边，所以不需要对它求值，直接抛弃这个整体。

Haskell 的内容太多了，高阶函数和惰性求值才仅仅是个开始，待我继续学习。
